//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFormsService.Web.Public.Views.Forms.ChildCareSubsidy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleFormsService.Web.Public.Views.Forms.ChildCareSubsidy.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted file types: &lt;abbr title=&quot;Portable Document Format&quot;&gt;pdf&lt;/abbr&gt;, &lt;abbr title=&quot;Joint Photographic Experts Group&quot;&gt;jpg&lt;/abbr&gt;.
        /// </summary>
        public static string AcceptedUploadType {
            get {
                return ResourceManager.GetString("AcceptedUploadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter applicant email.
        /// </summary>
        public static string ApplicantEmail_RequiredErr {
            get {
                return ResourceManager.GetString("ApplicantEmail_RequiredErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant information.
        /// </summary>
        public static string CCS_H2 {
            get {
                return ResourceManager.GetString("CCS_H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other information.
        /// </summary>
        public static string CCS_Other_H2 {
            get {
                return ResourceManager.GetString("CCS_Other_H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your completed application form and any digital supporting documents.
        /// </summary>
        public static string CCS_Submission {
            get {
                return ResourceManager.GetString("CCS_Submission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper documents may be delivered in-person or by mail; Digital documents may be uploaded through this form..
        /// </summary>
        public static string CCSDelivery_Both {
            get {
                return ResourceManager.GetString("CCSDelivery_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital documents may be uploaded through this form..
        /// </summary>
        public static string CCSDelivery_Digital {
            get {
                return ResourceManager.GetString("CCSDelivery_Digital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper documents may be dropped off or mailed to the regional &lt;abbr title=&quot;Education &amp; Early Childhood Development&quot;&gt;EECD&lt;/abbr&gt; office..
        /// </summary>
        public static string CCSDelivery_Paper {
            get {
                return ResourceManager.GetString("CCSDelivery_Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both paper and digital documents.
        /// </summary>
        public static string CCSFormat_Both {
            get {
                return ResourceManager.GetString("CCSFormat_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital documents.
        /// </summary>
        public static string CCSFormat_Digital {
            get {
                return ResourceManager.GetString("CCSFormat_Digital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper documents.
        /// </summary>
        public static string CCSFormat_Paper {
            get {
                return ResourceManager.GetString("CCSFormat_Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halifax.
        /// </summary>
        public static string CCSOffice_Halifax {
            get {
                return ResourceManager.GetString("CCSOffice_Halifax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kentville.
        /// </summary>
        public static string CCSOffice_Kentville {
            get {
                return ResourceManager.GetString("CCSOffice_Kentville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sydney.
        /// </summary>
        public static string CCSOffice_Sydney {
            get {
                return ResourceManager.GetString("CCSOffice_Sydney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truro.
        /// </summary>
        public static string CCSOffice_Truro {
            get {
                return ResourceManager.GetString("CCSOffice_Truro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yarmouth.
        /// </summary>
        public static string CCSOffice_Yarmouth {
            get {
                return ResourceManager.GetString("CCSOffice_Yarmouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Dropdown_Default {
            get {
                return ResourceManager.GetString("Dropdown_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Label_ApplicantEmail {
            get {
                return ResourceManager.GetString("Label_ApplicantEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Label_ApplicantName {
            get {
                return ResourceManager.GetString("Label_ApplicantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the closest regional &lt;abbr title=&quot;Education &amp; Early Childhood Development&quot;&gt;EECD&lt;/abbr&gt; office.
        /// </summary>
        public static string Label_RegionalOffice {
            get {
                return ResourceManager.GetString("Label_RegionalOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type of supporting documents will you provide?.
        /// </summary>
        public static string Label_SupportingDocument {
            get {
                return ResourceManager.GetString("Label_SupportingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum file size per file: 10 &lt;abbr title=&quot;megabyte&quot;&gt;MB&lt;/abbr&gt;.
        /// </summary>
        public static string MaxFileSize {
            get {
                return ResourceManager.GetString("MaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child care subsidy form.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
