//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFormsService.Web.Public.Views.Forms.SpecialPatientProgram {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleFormsService.Web.Public.Views.Forms.SpecialPatientProgram.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is invalid.
        /// </summary>
        public static string Email_FormatErr {
            get {
                return ResourceManager.GetString("Email_FormatErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be 150 characters or less.
        /// </summary>
        public static string Email_LengthErr {
            get {
                return ResourceManager.GetString("Email_LengthErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email.
        /// </summary>
        public static string Email_RequiredErr {
            get {
                return ResourceManager.GetString("Email_RequiredErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string Label_FileName {
            get {
                return ResourceManager.GetString("Label_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone number.
        /// </summary>
        public static string Label_Phone {
            get {
                return ResourceManager.GetString("Label_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission type.
        /// </summary>
        public static string Label_SubmissionType {
            get {
                return ResourceManager.GetString("Label_SubmissionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be 150 characters or less.
        /// </summary>
        public static string Name_LengthErr {
            get {
                return ResourceManager.GetString("Name_LengthErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special patient program.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is invalid.
        /// </summary>
        public static string Phone_FormatErr {
            get {
                return ResourceManager.GetString("Phone_FormatErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must be 14 characters or less.
        /// </summary>
        public static string Phone_LengthErr {
            get {
                return ResourceManager.GetString("Phone_LengthErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitter information.
        /// </summary>
        public static string SPP_H2 {
            get {
                return ResourceManager.GetString("SPP_H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the submission.
        /// </summary>
        public static string SPP_H2_2 {
            get {
                return ResourceManager.GetString("SPP_H2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your &lt;abbr title=&quot;Special patient program&quot;&gt;SPP&lt;/abbr&gt; submission.
        /// </summary>
        public static string SPP_Submission {
            get {
                return ResourceManager.GetString("SPP_Submission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated application.
        /// </summary>
        public static string SubmissionType_Existing {
            get {
                return ResourceManager.GetString("SubmissionType_Existing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New application.
        /// </summary>
        public static string SubmissionType_New {
            get {
                return ResourceManager.GetString("SubmissionType_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a submission type.
        /// </summary>
        public static string SubmissionType_RequiredErr {
            get {
                return ResourceManager.GetString("SubmissionType_RequiredErr", resourceCulture);
            }
        }
    }
}
