//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFormsService.Web.Public.Forms.ChildCareSubsidyReview {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleFormsService.Web.Public.Forms.ChildCareSubsidyReview.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted file types: &lt;abbr title=&quot;Portable Document Format&quot;&gt;pdf&lt;/abbr&gt;, &lt;abbr title=&quot;Joint Photographic Experts Group&quot;&gt;jpg&lt;/abbr&gt;.
        /// </summary>
        public static string AcceptedUploadType {
            get {
                return ResourceManager.GetString("AcceptedUploadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter applicant email.
        /// </summary>
        public static string ApplicantEmail_RequiredErr {
            get {
                return ResourceManager.GetString("ApplicantEmail_RequiredErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload the completed review form and any supporting documents.
        /// </summary>
        public static string CCSR_Submission {
            get {
                return ResourceManager.GetString("CCSR_Submission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select case worker.
        /// </summary>
        public static string Dropdown_Default {
            get {
                return ResourceManager.GetString("Dropdown_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant email.
        /// </summary>
        public static string Label_ApplicantEmail {
            get {
                return ResourceManager.GetString("Label_ApplicantEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant name.
        /// </summary>
        public static string Label_ApplicantName {
            get {
                return ResourceManager.GetString("Label_ApplicantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case worker.
        /// </summary>
        public static string Label_CaseWorker {
            get {
                return ResourceManager.GetString("Label_CaseWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Label_Upload {
            get {
                return ResourceManager.GetString("Label_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum file size per file: 10 &lt;abbr title=&quot;megabyte&quot;&gt;MB&lt;/abbr&gt;.
        /// </summary>
        public static string MaxFileSize {
            get {
                return ResourceManager.GetString("MaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child care subsidy review.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
