// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimpleFormsService.Domain.Entities.FormSubmission.Supporting.JSON;
using SimpleFormsService.Persistence;

#nullable disable

namespace SimpleFormsService.Persistence.Migrations
{
    [DbContext(typeof(SimpleFormsServiceDbContext))]
    partial class SimpleFormsServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimpleFormsService.Domain.Entities.FormSubmission.FormSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Create_Date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Create_User");

                    b.Property<FormSubmissionData>("SubmissionData")
                        .HasColumnType("jsonb")
                        .HasColumnName("Submission_Data");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("Template_Id");

                    b.Property<DateTime?>("UpdateDate")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Update_Date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UpdateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Update_User");

                    b.HasKey("Id");

                    b.ToTable("Form_Submission", (string)null);
                });

            modelBuilder.Entity("SimpleFormsService.Domain.Entities.FormTemplate.FormTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Create_Date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Create_User");

                    b.Property<DateTime?>("UpdateDate")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Update_Date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UpdateUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Update_User");

                    b.HasKey("Id");

                    b.ToTable("Form_Template", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
