// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimpleFormsService.Domain.Entities.Supporting.JSON;
using SimpleFormsService.Persistence;

#nullable disable

namespace SimpleFormsService.Persistence.Migrations
{
    [DbContext(typeof(SimpleFormsServiceDbContext))]
    partial class SimpleFormsServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimpleFormsService.Domain.Entities.FormSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<FormSubmissionData>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("Data");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("Template_Id");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("Form_Submission", (string)null);
                });

            modelBuilder.Entity("SimpleFormsService.Domain.Entities.FormTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<FormTemplateData>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("Data");

                    b.HasKey("Id");

                    b.ToTable("Form_Template", (string)null);
                });

            modelBuilder.Entity("SimpleFormsService.Domain.Entities.FormSubmission", b =>
                {
                    b.HasOne("SimpleFormsService.Domain.Entities.FormTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Template");
                });
#pragma warning restore 612, 618
        }
    }
}
