FROM mcr.microsoft.com/dotnet/sdk:6.0

WORKDIR /vsdbg

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
            unzip \
    && rm -rf /var/lib/apt/lists/* \
    && curl -sSL https://aka.ms/getvsdbgsh \
        | bash /dev/stdin -v latest -l /vsdbg \
    && apt-get update && apt-get install -y apt-utils libgdiplus libc6-dev

    ENV DOTNET_USE_POLLING_FILE_WATCHER 1

WORKDIR /app