//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFormsService.Web.Public.Forms.DrugInformationSystem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleFormsService.Web.Public.Forms.DrugInformationSystem.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted file types: &lt;abbr title=&quot;Portable Document Format&quot;&gt;pdf&lt;/abbr&gt;, &lt;abbr title=&quot;Joint Photographic Experts Group&quot;&gt;jpg&lt;/abbr&gt;.
        /// </summary>
        public static string AcceptedUploadType {
            get {
                return ResourceManager.GetString("AcceptedUploadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter contact name.
        /// </summary>
        public static string Contact_RequiredErr {
            get {
                return ResourceManager.GetString("Contact_RequiredErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload patient information to &lt;abbr title=&quot;Drug Information System&quot;&gt;DIS&lt;/abbr&gt; support. .
        /// </summary>
        public static string DIS_Upload {
            get {
                return ResourceManager.GetString("DIS_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All patient confidential information should be sent as an attachment..
        /// </summary>
        public static string DIS_UploadNote {
            get {
                return ResourceManager.GetString("DIS_UploadNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter from email.
        /// </summary>
        public static string DISEmail_RequiredErr {
            get {
                return ResourceManager.GetString("DISEmail_RequiredErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Dropdown_Default {
            get {
                return ResourceManager.GetString("Dropdown_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is optional.
        /// </summary>
        public static string Hint_Optional {
            get {
                return ResourceManager.GetString("Hint_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the selected source type.
        /// </summary>
        public static string Hint_SourceName {
            get {
                return ResourceManager.GetString("Hint_SourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact name.
        /// </summary>
        public static string Label_Contact {
            get {
                return ResourceManager.GetString("Label_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From email.
        /// </summary>
        public static string Label_DISEmail {
            get {
                return ResourceManager.GetString("Label_DISEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;abbr title=&quot;Drug Information System&quot;&gt;DIS&lt;/abbr&gt; service desk ticket number.
        /// </summary>
        public static string Label_DISTicket {
            get {
                return ResourceManager.GetString("Label_DISTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Label_Org {
            get {
                return ResourceManager.GetString("Label_Org", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy.
        /// </summary>
        public static string Label_Pharmacy {
            get {
                return ResourceManager.GetString("Label_Pharmacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source name.
        /// </summary>
        public static string Label_Source {
            get {
                return ResourceManager.GetString("Label_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a source type.
        /// </summary>
        public static string Label_SourceType {
            get {
                return ResourceManager.GetString("Label_SourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Label_Subject {
            get {
                return ResourceManager.GetString("Label_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software vendor.
        /// </summary>
        public static string Label_Vendor {
            get {
                return ResourceManager.GetString("Label_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor ticket number.
        /// </summary>
        public static string Label_VendorTicketNumber {
            get {
                return ResourceManager.GetString("Label_VendorTicketNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum file size per file: 10 &lt;abbr title=&quot;megabyte&quot;&gt;MB&lt;/abbr&gt;.
        /// </summary>
        public static string MaxFileSize {
            get {
                return ResourceManager.GetString("MaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug information system form.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter pharmacy / vendor / organization.
        /// </summary>
        public static string Source_RequiredErr {
            get {
                return ResourceManager.GetString("Source_RequiredErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your subject.
        /// </summary>
        public static string Subject_RequiredErr {
            get {
                return ResourceManager.GetString("Subject_RequiredErr", resourceCulture);
            }
        }
    }
}
