//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFormsService.Web.Admin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleFormsService.Web.Admin.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple forms service admin &lt;abbr title=&quot;User Interface&quot;&gt;UI&lt;/abbr&gt;.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filter.
        /// </summary>
        public static string Btn_ClearFilter {
            get {
                return ResourceManager.GetString("Btn_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close application.
        /// </summary>
        public static string Btn_CloseApp {
            get {
                return ResourceManager.GetString("Btn_CloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Btn_SignOut {
            get {
                return ResourceManager.GetString("Btn_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update status.
        /// </summary>
        public static string Btn_UpdateStatus {
            get {
                return ResourceManager.GetString("Btn_UpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Btn_View {
            get {
                return ResourceManager.GetString("Btn_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://beta.novascotia.ca/copyright/.
        /// </summary>
        public static string CrownCopyRight_href {
            get {
                return ResourceManager.GetString("CrownCopyRight_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government of Nova Scotia.
        /// </summary>
        public static string GNS {
            get {
                return ResourceManager.GetString("GNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form ID.
        /// </summary>
        public static string Label_FormID {
            get {
                return ResourceManager.GetString("Label_FormID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Label_Home {
            get {
                return ResourceManager.GetString("Label_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission date.
        /// </summary>
        public static string Label_SubmissionDate {
            get {
                return ResourceManager.GetString("Label_SubmissionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission ID.
        /// </summary>
        public static string Label_SubmissionID {
            get {
                return ResourceManager.GetString("Label_SubmissionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter last name.
        /// </summary>
        public static string LastName_RequiredErr {
            get {
                return ResourceManager.GetString("LastName_RequiredErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crown copyright © Government of Nova Scotia.
        /// </summary>
        public static string Link_CrownCopyRight {
            get {
                return ResourceManager.GetString("Link_CrownCopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Link_Edit {
            get {
                return ResourceManager.GetString("Link_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Link_Privacy {
            get {
                return ResourceManager.GetString("Link_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string Link_Terms {
            get {
                return ResourceManager.GetString("Link_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://novascotia.ca/clf/ignition/img/nsvip-en-white-flag.svg.
        /// </summary>
        public static string Logo_link {
            get {
                return ResourceManager.GetString("Logo_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://beta.novascotia.ca/privacy/.
        /// </summary>
        public static string Privacy_href {
            get {
                return ResourceManager.GetString("Privacy_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the submission.
        /// </summary>
        public static string Section_Submission {
            get {
                return ResourceManager.GetString("Section_Submission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission detail.
        /// </summary>
        public static string Section_SubmissionDetail {
            get {
                return ResourceManager.GetString("Section_SubmissionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://beta.novascotia.ca/terms/.
        /// </summary>
        public static string Terms_href {
            get {
                return ResourceManager.GetString("Terms_href", resourceCulture);
            }
        }
    }
}
