//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFormsService.Web.Public.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleFormsService.Web.Public.Views.Shared.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted file types: &lt;abbr title=&quot;Document/Documentation&quot;&gt;doc(x)&lt;/abbr&gt;, &lt;abbr title=&quot;Joint Photographic Experts Group&quot;&gt;jp(e)g&lt;/abbr&gt;, &lt;abbr title=&quot;Portable Document Format&quot;&gt;pdf&lt;/abbr&gt;, &lt;abbr title=&quot;Portable Graphics Format&quot;&gt;png&lt;/abbr&gt;, .
        /// </summary>
        public static string AcceptedUploadType {
            get {
                return ResourceManager.GetString("AcceptedUploadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple forms service.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Btn_Submit {
            get {
                return ResourceManager.GetString("Btn_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove file.
        /// </summary>
        public static string Caption_RemoveFile {
            get {
                return ResourceManager.GetString("Caption_RemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded file(s).
        /// </summary>
        public static string Caption_UploadedFile {
            get {
                return ResourceManager.GetString("Caption_UploadedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://beta.novascotia.ca/copyright/.
        /// </summary>
        public static string CrownCopyRight_href {
            get {
                return ResourceManager.GetString("CrownCopyRight_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email specified.
        /// </summary>
        public static string FormItem_EmailInvalidErr {
            get {
                return ResourceManager.GetString("FormItem_EmailInvalidErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address must be 150 characters or less.
        /// </summary>
        public static string FormItem_EmailStringLengthErr {
            get {
                return ResourceManager.GetString("FormItem_EmailStringLengthErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a required field and cannot be blank.
        /// </summary>
        public static string FormItem_FieldRequiredErr {
            get {
                return ResourceManager.GetString("FormItem_FieldRequiredErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ID must be 150 characters or less.
        /// </summary>
        public static string FormItem_IDStringLengthErr {
            get {
                return ResourceManager.GetString("FormItem_IDStringLengthErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name must be 150 characters or less.
        /// </summary>
        public static string FormItem_NameStringLengthErr {
            get {
                return ResourceManager.GetString("FormItem_NameStringLengthErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This number must be 150 characters or less.
        /// </summary>
        public static string FormItem_NumberStringLengthErr {
            get {
                return ResourceManager.GetString("FormItem_NumberStringLengthErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid telephone number specified.
        /// </summary>
        public static string FormItem_PhoneInvalidErr {
            get {
                return ResourceManager.GetString("FormItem_PhoneInvalidErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This telephone number must be 14 digits or less.
        /// </summary>
        public static string FormItem_PhoneStringLengthErr {
            get {
                return ResourceManager.GetString("FormItem_PhoneStringLengthErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required and an option must be selected.
        /// </summary>
        public static string FormItem_SelectRequiredErr {
            get {
                return ResourceManager.GetString("FormItem_SelectRequiredErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message must be 2000 characters or less.
        /// </summary>
        public static string FormItem_TextareaStringLengthErr {
            get {
                return ResourceManager.GetString("FormItem_TextareaStringLengthErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This text must be 150 characters or less.
        /// </summary>
        public static string FormItem_TextStringLengthErr {
            get {
                return ResourceManager.GetString("FormItem_TextStringLengthErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is optional.
        /// </summary>
        public static string Hint_OptionalField {
            get {
                return ResourceManager.GetString("Hint_OptionalField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name(s):.
        /// </summary>
        public static string Label_FileName {
            get {
                return ResourceManager.GetString("Label_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Label_Remove {
            get {
                return ResourceManager.GetString("Label_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload document(s).
        /// </summary>
        public static string Label_Upload {
            get {
                return ResourceManager.GetString("Label_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crown copyright © Government of Nova Scotia.
        /// </summary>
        public static string Link_CrownCopyRight {
            get {
                return ResourceManager.GetString("Link_CrownCopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Link_Privacy {
            get {
                return ResourceManager.GetString("Link_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string Link_Terms {
            get {
                return ResourceManager.GetString("Link_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://novascotia.ca/clf/ignition/img/nsvip-en-white-flag.svg.
        /// </summary>
        public static string Logo_link {
            get {
                return ResourceManager.GetString("Logo_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://novascotia.ca/clf/ignition/img/nsvip-en.svg.
        /// </summary>
        public static string PrintLogo_link {
            get {
                return ResourceManager.GetString("PrintLogo_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://beta.novascotia.ca/privacy/.
        /// </summary>
        public static string Privacy_href {
            get {
                return ResourceManager.GetString("Privacy_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Forms service - Government of Nova Scotia.
        /// </summary>
        public static string Shared_PageTitle {
            get {
                return ResourceManager.GetString("Shared_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://beta.novascotia.ca/terms/.
        /// </summary>
        public static string Terms_href {
            get {
                return ResourceManager.GetString("Terms_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .doc,.docx,.jpeg,.jpg,.pdf,.png.
        /// </summary>
        public static string Upload_AllowedTypes {
            get {
                return ResourceManager.GetString("Upload_AllowedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot upload duplicate files.
        /// </summary>
        public static string Upload_DuplicateErr {
            get {
                return ResourceManager.GetString("Upload_DuplicateErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File must be less than 10 MB.
        /// </summary>
        public static string Upload_FileSizeErr {
            get {
                return ResourceManager.GetString("Upload_FileSizeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type not supported.
        /// </summary>
        public static string Upload_FileTypeErr {
            get {
                return ResourceManager.GetString("Upload_FileTypeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum file size per file: 10 &lt;abbr title=&quot;megabyte&quot;&gt;MB&lt;/abbr&gt;.
        /// </summary>
        public static string Upload_MaxFileSize {
            get {
                return ResourceManager.GetString("Upload_MaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your document(s).
        /// </summary>
        public static string Upload_RequiredErr {
            get {
                return ResourceManager.GetString("Upload_RequiredErr", resourceCulture);
            }
        }
    }
}
